### ISSUE TITLE
How do I deploy an SSL certificate for a related component in K8S? For example, minio.

### ISSUE THREAD

**Issue by caesar168** [openimsdk/helm-charts#9]
### What would you like to share?

How do I deploy an SSL certificate for a related component in K8S? For example, minio.

**Comment by cubxxw** [comment]
After reading the article you provided at https://github.com/openimsdk/helm-charts/tree/main/infra/minio, I would suggest searching for `tls.enabled` on the page to determine if setting it to false can resolve the authentication issue with Minio in the container. Thank you for bringing this to my attention and I hope this solution proves helpful.

**Comment by cubxxw** [comment]
@caesar168  You can configure this field in the following file: https://github.com/openimsdk/helm-charts/blob/main/infra/minio-config.yaml. Thank you for considering this option.

```
apiIngress:
  enabled: true
  ingressClassName: "nginx"
  hostname: openim.server.com # your hostname
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  path: /im-minio-api(/|$)(.*)
  pathType: ImplementationSpecific
  servicePort: minio-api
  extraTls:
    - hosts:
        - openim.server.com
      secretName: webapitls  #your hostname tls
```
